In [1]:
import numpy as np
import pandas as pd

基本数据类型

In [2]:
#整数
a=10
type(a)

int

In [3]:
a.bit_length()

4

In [4]:
a=100000
a.bit_length()

17

In [9]:
googol=10**100
googol

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [10]:
googol.bit_length()

333

In [11]:
type(1/4)

float

In [12]:
#浮点数
1./4

0.25

In [13]:
b=0.35
type(b)

float

In [14]:
b+0.1

0.44999999999999996

In [15]:
c=0.5
c.as_integer_ratio()

(1, 2)

In [16]:
b.as_integer_ratio()

(3152519739159347, 9007199254740992)

In [17]:
import decimal
from decimal import Decimal
decimal.getcontext()

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])

In [19]:
d = Decimal(1)/Decimal(11)
d

Decimal('0.09090909090909090909090909091')

In [21]:
decimal.getcontext().prec=4
e=Decimal(1)/Decimal(11)
e

Decimal('0.09091')

In [23]:
decimal.getcontext().prec=50
f=Decimal(1)/Decimal(11)
f

Decimal('0.090909090909090909090909090909090909090909090909091')

In [25]:
g=d+e+f
g

Decimal('0.27272818181818181818181818181909090909090909090909')

In [26]:
#字符串
t='this is a string object'
t.capitalize()

'This is a string object'

In [27]:
t.split()

['this', 'is', 'a', 'string', 'object']

In [28]:
t.find('string')

10

In [29]:
t.find('Python')

-1

In [30]:
t.replace(' ','|')

'this|is|a|string|object'

In [31]:
'http://www.python.org'.strip('htp:/')

'www.python.org'

In [32]:
import re
series="""
'01/18/2014 13:00:00',100,'1st';
'01/18/2014 13:30:00',110,'2nd';
'01/18/2014 14:00:00',120,'3rd';
"""
dt=re.compile("'[0-9/:\s]+'")
result = dt.findall(series)
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [33]:
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'",""),
                        '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [35]:
print(pydt)

2014-01-18 13:00:00


In [36]:
print(type(pydt))

<class 'datetime.datetime'>


基本数据结构

In [37]:
#tuple
t = (1,2.5,'data')
type(t)

tuple

In [38]:
t = 1,2.5 ,'data'
type(t)

tuple

In [39]:
t[2]

'data'

In [40]:
type(t[2])

str

In [41]:
t.count('data')

1

In [42]:
t.index(1)

0

In [53]:
#list
l=[1,2.5,'data']
l[2]

'data'

In [54]:
l=list(t)
l

[1, 2.5, 'data']

In [55]:
[1,2.5,'data']
type(l)

list

In [56]:
l.append([4,3])
l

[1, 2.5, 'data', [4, 3]]

In [57]:
[1,2.5,'data',[4,3]]
l.extend([1.0,1.5,2.0])
l

[1, 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [58]:
l.insert(1,'insert')
l

[1, 'insert', 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [59]:
l.remove('data')
l

[1, 'insert', 2.5, [4, 3], 1.0, 1.5, 2.0]

In [61]:
p = l.pop(3)
print(l,p)

[1, 'insert', 2.5, 1.0, 1.5, 2.0] [4, 3]


In [62]:
l[2:5]

[2.5, 1.0, 1.5]

In [63]:
#控制结构
for element in l[2:5]:
    print(element**2)

6.25
1.0
2.25


In [64]:
r =range(0,8,1)
r

range(0, 8)

In [65]:
type(r)

range

In [66]:
for i in range(2,5):
    print(l[i]**2)

6.25
1.0
2.25


In [67]:
for i in range(1,10):
    if i%2==0:
        print("%d is even"%i)
    elif i%3==0:
        print("%d is multiple of 3"%i)
    else:
        print("%d is odd"%i)

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


In [69]:
total =0
while total <100:
    total +=1
print(total)

100


In [70]:
m= [i**2 for i in range(5)]
m

[0, 1, 4, 9, 16]

In [72]:
#函数式编程
def f(x):
    return x**2
f(2)

4

In [73]:
def even(x):
    return x%2 ==0
even(3)

False

In [82]:
a= map(even, range(10))
for i in a:
    print(i)

True
False
True
False
True
False
True
False
True
False


In [83]:
b = map(lambda x:x*2, range(10))
print(b)

In [78]:
filter(even,range(10))

In [84]:
from functools import reduce
#python 3以上版本reduce需要另外调用#
reduce(lambda x,y: x+y,range(10))

45

In [80]:
def cumsum(l):
    total=0
    for elem in l:
        total += elem
    return total
cumsum(range(10))

45

In [86]:
#字典
d = {'Name':'Angela',
     'Country':'Germany',
     'Profession':'Chancelor',
     'Age':60}
type(d)

dict

In [87]:
d.keys()

dict_keys(['Name', 'Country', 'Profession', 'Age'])

In [88]:
d.values()

dict_values(['Angela', 'Germany', 'Chancelor', 60])

In [89]:
d.items()

dict_items([('Name', 'Angela'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 60)])

In [90]:
birthday=True
if birthday is True:
    d['Age'] +=1
print(d['Age'])

61


In [92]:
for item in d.items():
    print(item)

('Name', 'Angela')
('Country', 'Germany')
('Profession', 'Chancelor')
('Age', 61)


In [94]:
for value in d.values():
    print(type(value))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'int'>


In [95]:
#集合
s = set(['u','d','ud','du','d','du'])
s

{'d', 'du', 'u', 'ud'}

In [96]:
t=set(['d','dd','uu','u'])
s.union(t)

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [97]:
s.intersection(t)

{'d', 'u'}

In [98]:
s.difference(t)

{'du', 'ud'}

In [99]:
t.difference(s)

{'dd', 'uu'}

In [100]:
s.symmetric_difference(t)

{'dd', 'du', 'ud', 'uu'}

In [102]:
from random import randint
l = [randint(0,10) for i in range(1000)]
len(l)

1000

In [103]:
l[:20]

[2, 1, 0, 7, 7, 9, 0, 3, 1, 3, 4, 7, 6, 5, 7, 2, 9, 2, 4, 9]

In [105]:
s=set(l)
s

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

Numpy数据结构

In [106]:
#用python列表形成数组
v = [0.5,0.75,1.0,1.5,2.0]

In [107]:
m=[v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [109]:
v[0]='Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [110]:
from copy import deepcopy
v=[0.5,0.75,1.0,1.5,2.0]
m=3*[deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [111]:
v[0]='Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [112]:
#常规Numpy数组
a = np.array([0,0.5,1.0,1.5,2.0])
type(a)

numpy.ndarray

In [113]:
a[:2]

array([0. , 0.5])

In [114]:
a.sum()

5.0

In [115]:
a.std()

0.7071067811865476

In [116]:
a.cumsum()

array([0. , 0.5, 1.5, 3. , 5. ])

In [117]:
a*2

array([0., 1., 2., 3., 4.])

In [118]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [120]:
b=np.array([a,a*2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [121]:
b[0]

array([0. , 0.5, 1. , 1.5, 2. ])

In [122]:
b[0,2]

1.0

In [123]:
b.sum()

15.0

In [124]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[0.  1.5 3.  4.5 6. ]
[ 5. 10.]


In [125]:
c=np.zeros((2,3,4),dtype='i',order='C')
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [127]:
d= np.ones_like(c, dtype='float',order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [128]:
import random
I=5000
%time mat = [[random.gauss(0,1) for j in range(I)] for i in range(I)]

Wall time: 31.7 s


In [130]:
#结构数组
dt=np.dtype([('Name','S10'),('Age','i4'),
            ('Height','f'),('Children/Pets','i4',2)])
s = np.array([('Smith',45,1.83,(0,1)),
             ('Jones',53,1.72,(2,2))],dtype=dt)
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [131]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [132]:
s['Height'].mean()

1.7750001

In [133]:
s[1]['Age']

53

代码向量化

In [134]:
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))
r+s

array([[ 1.46813076, -4.86144782, -2.79792804],
       [ 0.5225424 ,  3.05659211,  1.30147291],
       [-0.19085277, -2.83625263,  0.23268515],
       [-1.03102749, -1.8349908 ,  1.75189155]])

In [135]:
2*r+3

array([[1.8875231 , 0.46714992, 1.02159175],
       [3.21611804, 5.80920568, 4.50722466],
       [4.36411893, 0.98240328, 4.47019985],
       [3.34704908, 1.53644604, 6.32169222]])

In [136]:
s= np.random.standard_normal(3)
r+s

array([[-3.52668398, -0.07150069, -0.64162194],
       [-2.86238651,  2.59952719,  1.10119451],
       [-2.28838606,  0.18612599,  1.0826821 ],
       [-2.79692099,  0.46314737,  2.00842829]])

In [137]:
s=np.random.standard_normal(4)
r+s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [138]:
r.transpose()+s

array([[-1.42082915, -0.00302838,  1.1578684 ,  0.16217151],
       [-2.13101573,  1.29351544, -0.53298943, -0.74313001],
       [-1.85379482,  0.64252493,  1.21090885,  1.64949308]])

In [139]:
np.shape(r.T)

(3, 4)

In [141]:
def f(x):
    return 3*x + 5
f(0.5)

6.5

In [142]:
f(r)

array([[3.33128464, 1.20072488, 2.03238763],
       [5.32417706, 9.21380853, 7.260837  ],
       [7.0461784 , 1.97360492, 7.20529977],
       [5.52057363, 2.80466906, 9.98253833]])

In [143]:
import math
math.sin(r)   #math不能直接调用

TypeError: only size-1 arrays can be converted to Python scalars

In [144]:
np.sin(r)

array([[-0.52799546, -0.95403556, -0.83558902],
       [ 0.10784885,  0.98622162,  0.68427741],
       [ 0.63039307, -0.84619213,  0.67066128],
       [ 0.17265503, -0.66819274,  0.99594826]])

In [145]:
np.sin(np.pi)

1.2246467991473532e-16

内存布局

In [146]:
x=np.random.standard_normal((5,10000000))
y=2*x+3
C=np.array((x,y),order='C')
F=np.array((x,y),order='F')
x=0.0; y=0.0
C[:2].round(2)

array([[[ 0.32, -0.29, -1.81, ..., -0.28,  0.66, -0.33],
        [-1.46, -0.29, -0.2 , ...,  1.38,  0.6 ,  0.01],
        [ 1.  ,  0.74, -0.15, ..., -3.27, -1.57,  1.37],
        [ 1.63, -1.13, -1.94, ...,  0.19, -0.41,  0.86],
        [ 2.6 ,  0.94, -0.45, ..., -1.04, -0.43,  0.68]],

       [[ 3.64,  2.42, -0.62, ...,  2.45,  4.31,  2.33],
        [ 0.07,  2.43,  2.59, ...,  5.77,  4.2 ,  3.01],
        [ 5.  ,  4.48,  2.69, ..., -3.54, -0.14,  5.73],
        [ 6.26,  0.75, -0.88, ...,  3.38,  2.19,  4.71],
        [ 8.19,  4.89,  2.09, ...,  0.92,  2.14,  4.37]]])

In [147]:
%timeit C.sum()

149 ms ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [148]:
%timeit F.sum()

146 ms ± 7.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [149]:
%timeit C[0].sum(axis=0)

129 ms ± 2.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [150]:
%timeit C[0].sum(axis=1)

80.7 ms ± 7.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [151]:
%timeit F.sum(axis=0)

1.03 s ± 55.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [152]:
%timeit F.sum(axis=1)

2.68 s ± 153 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [153]:
F=0.0; C=0.0 #memory clearup